connections {
    ikev2-vpn {
        version = 2
        send_cert = always
        encap = yes
        fragmentation = yes
        pools = rw_pool
        unique = never

        proposals = aes256-sha256-modp2048,aes256-sha256-modp1024

        local {
            auth = pubkey
            certs = server-cert.pem
            id = vpnyourdomaincom
        }

        remote {
            auth = eap-mschapv2
            eap_id = %any
        }

        children {
            ikev2-child {
                local_ts = 0.0.0.0/0
            }
        }

    }
}

pools {
    rw_pool {
        addrs = 10.10.10.0/24
        dns = 8.8.8.8
    }
}

# 引入挂载的多用户及额外配置
include conf.d/*.conf
